In [ ]:
import numpy as np
import pandas as pd

In [4]:
df = pd.DataFrame(np.random.randn(5,4)) 
df

          0         1         2         3
0 -0.570042 -0.714993  0.649850 -1.010631
1  0.760107  0.975499  1.347916  1.976495
2 -1.278069  0.400469  0.567650 -1.931165
3 -0.912314 -0.409440  0.282925  0.829117
4 -1.619347  0.251805  1.578621  0.984054

In [5]:
df.columns = ['A','B','C','D']

In [6]:
df

          A         B         C         D
0 -0.570042 -0.714993  0.649850 -1.010631
1  0.760107  0.975499  1.347916  1.976495
2 -1.278069  0.400469  0.567650 -1.931165
3 -0.912314 -0.409440  0.282925  0.829117
4 -1.619347  0.251805  1.578621  0.984054

In [7]:
df.index = pd.date_range("20200214", periods=5)

In [8]:
df

                   A         B         C         D
2020-02-14 -0.570042 -0.714993  0.649850 -1.010631
2020-02-15  0.760107  0.975499  1.347916  1.976495
2020-02-16 -1.278069  0.400469  0.567650 -1.931165
2020-02-17 -0.912314 -0.409440  0.282925  0.829117
2020-02-18 -1.619347  0.251805  1.578621  0.984054

In [9]:
type(df.index)

pandas.DatetimeIndex

In [10]:
df['E'] = [9.9, np.nan, 10, 9.8, np.nan]

In [11]:
df

                   A         B         C         D     E
2020-02-14 -0.570042 -0.714993  0.649850 -1.010631   9.9
2020-02-15  0.760107  0.975499  1.347916  1.976495   NaN
2020-02-16 -1.278069  0.400469  0.567650 -1.931165  10.0
2020-02-17 -0.912314 -0.409440  0.282925  0.829117   9.8
2020-02-18 -1.619347  0.251805  1.578621  0.984054   NaN

In [ ]:
#df.drop?

In [ ]:
#df.dropna?

In [12]:
df.dropna(how='any')

                   A         B         C         D     E
2020-02-14 -0.570042 -0.714993  0.649850 -1.010631   9.9
2020-02-16 -1.278069  0.400469  0.567650 -1.931165  10.0
2020-02-17 -0.912314 -0.409440  0.282925  0.829117   9.8

In [13]:
df

                   A         B         C         D     E
2020-02-14 -0.570042 -0.714993  0.649850 -1.010631   9.9
2020-02-15  0.760107  0.975499  1.347916  1.976495   NaN
2020-02-16 -1.278069  0.400469  0.567650 -1.931165  10.0
2020-02-17 -0.912314 -0.409440  0.282925  0.829117   9.8
2020-02-18 -1.619347  0.251805  1.578621  0.984054   NaN

In [14]:
df.dropna(how='all')

                   A         B         C         D     E
2020-02-14 -0.570042 -0.714993  0.649850 -1.010631   9.9
2020-02-15  0.760107  0.975499  1.347916  1.976495   NaN
2020-02-16 -1.278069  0.400469  0.567650 -1.931165  10.0
2020-02-17 -0.912314 -0.409440  0.282925  0.829117   9.8
2020-02-18 -1.619347  0.251805  1.578621  0.984054   NaN

In [15]:
df.fillna(value=9.7)

                   A         B         C         D     E
2020-02-14 -0.570042 -0.714993  0.649850 -1.010631   9.9
2020-02-15  0.760107  0.975499  1.347916  1.976495   9.7
2020-02-16 -1.278069  0.400469  0.567650 -1.931165  10.0
2020-02-17 -0.912314 -0.409440  0.282925  0.829117   9.8
2020-02-18 -1.619347  0.251805  1.578621  0.984054   9.7

In [16]:
df

                   A         B         C         D     E
2020-02-14 -0.570042 -0.714993  0.649850 -1.010631   9.9
2020-02-15  0.760107  0.975499  1.347916  1.976495   NaN
2020-02-16 -1.278069  0.400469  0.567650 -1.931165  10.0
2020-02-17 -0.912314 -0.409440  0.282925  0.829117   9.8
2020-02-18 -1.619347  0.251805  1.578621  0.984054   NaN

In [17]:
df.fillna(value=9.7, inplace=True)

                   A         B         C         D     E
2020-02-14 -0.570042 -0.714993  0.649850 -1.010631   9.9
2020-02-15  0.760107  0.975499  1.347916  1.976495   9.7
2020-02-16 -1.278069  0.400469  0.567650 -1.931165  10.0
2020-02-17 -0.912314 -0.409440  0.282925  0.829117   9.8
2020-02-18 -1.619347  0.251805  1.578621  0.984054   9.7

In [18]:
df

                   A         B         C         D     E
2020-02-14 -0.570042 -0.714993  0.649850 -1.010631   9.9
2020-02-15  0.760107  0.975499  1.347916  1.976495   9.7
2020-02-16 -1.278069  0.400469  0.567650 -1.931165  10.0
2020-02-17 -0.912314 -0.409440  0.282925  0.829117   9.8
2020-02-18 -1.619347  0.251805  1.578621  0.984054   9.7

In [ ]:
pd.to_datetime('20200214') # 문자열 형태의 날짜를 날짜 타입(datetime)으로 반환

Timestamp('2020-02-14 00:00:00')

In [21]:
df.drop(pd.to_datetime('20200214'))

                   A         B         C         D     E
2020-02-15  0.760107  0.975499  1.347916  1.976495   9.7
2020-02-16 -1.278069  0.400469  0.567650 -1.931165  10.0
2020-02-17 -0.912314 -0.409440  0.282925  0.829117   9.8
2020-02-18 -1.619347  0.251805  1.578621  0.984054   9.7

In [22]:
df

                   A         B         C         D     E
2020-02-14 -0.570042 -0.714993  0.649850 -1.010631   9.9
2020-02-15  0.760107  0.975499  1.347916  1.976495   9.7
2020-02-16 -1.278069  0.400469  0.567650 -1.931165  10.0
2020-02-17 -0.912314 -0.409440  0.282925  0.829117   9.8
2020-02-18 -1.619347  0.251805  1.578621  0.984054   9.7

In [23]:
df.drop([pd.to_datetime('20200214') ,pd.to_datetime('20200216')  ])

                   A         B         C         D    E
2020-02-15  0.760107  0.975499  1.347916  1.976495  9.7
2020-02-17 -0.912314 -0.409440  0.282925  0.829117  9.8
2020-02-18 -1.619347  0.251805  1.578621  0.984054  9.7

In [24]:
df

                   A         B         C         D     E
2020-02-14 -0.570042 -0.714993  0.649850 -1.010631   9.9
2020-02-15  0.760107  0.975499  1.347916  1.976495   9.7
2020-02-16 -1.278069  0.400469  0.567650 -1.931165  10.0
2020-02-17 -0.912314 -0.409440  0.282925  0.829117   9.8
2020-02-18 -1.619347  0.251805  1.578621  0.984054   9.7

In [25]:
df.drop('E', axis=1)

                   A         B         C         D
2020-02-14 -0.570042 -0.714993  0.649850 -1.010631
2020-02-15  0.760107  0.975499  1.347916  1.976495
2020-02-16 -1.278069  0.400469  0.567650 -1.931165
2020-02-17 -0.912314 -0.409440  0.282925  0.829117
2020-02-18 -1.619347  0.251805  1.578621  0.984054

In [26]:
df

                   A         B         C         D     E
2020-02-14 -0.570042 -0.714993  0.649850 -1.010631   9.9
2020-02-15  0.760107  0.975499  1.347916  1.976495   9.7
2020-02-16 -1.278069  0.400469  0.567650 -1.931165  10.0
2020-02-17 -0.912314 -0.409440  0.282925  0.829117   9.8
2020-02-18 -1.619347  0.251805  1.578621  0.984054   9.7

In [27]:
df.drop(['B','D'], axis=1)

                   A         C     E
2020-02-14 -0.570042  0.649850   9.9
2020-02-15  0.760107  1.347916   9.7
2020-02-16 -1.278069  0.567650  10.0
2020-02-17 -0.912314  0.282925   9.8
2020-02-18 -1.619347  1.578621   9.7

In [ ]:
df.drop(df.index[1])

In [ ]:
df.drop(df.index[[1,3]])

In [ ]:
df.drop(df.index[1:3])

In [ ]:
df.drop(df.columns[1:3], axis=1)

In [ ]:
df.drop(df.columns[0], axis=1)

In [28]:
df

                   A         B         C         D     E
2020-02-14 -0.570042 -0.714993  0.649850 -1.010631   9.9
2020-02-15  0.760107  0.975499  1.347916  1.976495   9.7
2020-02-16 -1.278069  0.400469  0.567650 -1.931165  10.0
2020-02-17 -0.912314 -0.409440  0.282925  0.829117   9.8
2020-02-18 -1.619347  0.251805  1.578621  0.984054   9.7

In [ ]:
df.drop('E', axis=1, inplace=True)
df