In [1]:
import numpy as np
import pandas as pd

In [2]:
data = [[9.9, 8.8], [np.nan, 6.6],[7.7, np.nan],  [0.99, 9.8]]
df = pd.DataFrame(data, columns=["first", "second"], index=["a", "b", "c", "d"])

In [3]:
df

   first  second
a   9.90     8.8
b    NaN     6.6
c   7.70     NaN
d   0.99     9.8

In [4]:
df.sum(axis=0)

first     18.59
second    25.20
dtype: float64

In [5]:
#df.sum?

In [6]:
df.sum(axis=0, skipna=False)

first    NaN
second   NaN
dtype: float64

In [7]:
df.sum(axis=1)

a    18.70
b     6.60
c     7.70
d    10.79
dtype: float64

In [8]:
df.sum(axis=1, skipna=False)

a    18.70
b      NaN
c      NaN
d    10.79
dtype: float64

In [9]:
df

   first  second
a   9.90     8.8
b    NaN     6.6
c   7.70     NaN
d   0.99     9.8

In [10]:
df.describe()

          first    second
count  3.000000  3.000000
mean   6.196667  8.400000
std    4.641340  1.637071
min    0.990000  6.600000
25%    4.345000  7.700000
50%    7.700000  8.800000
75%    8.800000  9.300000
max    9.900000  9.800000

In [11]:
df

   first  second
a   9.90     8.8
b    NaN     6.6
c   7.70     NaN
d   0.99     9.8

In [12]:
df['first'].sum()

np.float64(18.59)

In [13]:
df.loc['a'].sum()

np.float64(18.700000000000003)

In [14]:
df.mean(axis=1)

a    9.350
b    6.600
c    7.700
d    5.395
dtype: float64

In [15]:
df

   first  second
a   9.90     8.8
b    NaN     6.6
c   7.70     NaN
d   0.99     9.8

In [16]:
first_mean = df.mean(axis=0)['first']

In [17]:
second_min = df.min(axis=0)['second']

In [18]:
df['first'] = df['first'].fillna(value=first_mean)

In [19]:
df['second'] = df['second'].fillna(value=second_min)

In [20]:
df

      first  second
a  9.900000     8.8
b  6.196667     6.6
c  7.700000     6.6
d  0.990000     9.8

In [21]:
df2 = pd.DataFrame(np.random.randn(6, 4),
                   columns=["A", "B", "C", "D"],
                   index=pd.date_range("20180220", periods=6)) 
df2

                   A         B         C         D
2018-02-20  0.031322  1.402828 -0.021302 -0.253793
2018-02-21 -0.964640 -0.448283 -0.428961  0.558963
2018-02-22 -0.338259 -0.494666  0.448117  0.548631
2018-02-23  1.301426 -0.197857 -0.296553  1.898996
2018-02-24  0.593048  1.031520  0.737622 -0.308144
2018-02-25  0.178941 -0.280785  1.255342 -0.268857

In [22]:
df2['A'].corr(df2['B'])

np.float64(0.2527581445354628)

In [23]:
df2['A'].corr(df2['C'])

np.float64(0.12324277222428462)

In [24]:
df2['A'].corr(df2['D'])

np.float64(0.3661875103773995)

In [25]:
df2.corr()

          A         B         C         D
A  1.000000  0.252758  0.123243  0.366188
B  0.252758  1.000000  0.045271 -0.526151
C  0.123243  0.045271  1.000000 -0.621954
D  0.366188 -0.526151 -0.621954  1.000000

In [26]:
df2.cov()

          A         B         C         D
A  0.603242  0.162470  0.062252  0.243410
B  0.162470  0.684931  0.024366 -0.372669
C  0.062252  0.024366  0.422952 -0.346173
D  0.243410 -0.372669 -0.346173  0.732451

In [27]:
dates = df2.index
# permutation 은 치환
random_dates = np.random.permutation(dates)
# 무작위로 섞어봄. index 순서와 컬럼의 순서가 불규칙하게 변함
df2 = df2.reindex(index=random_dates, columns=["D", "B", "C", "A"])

In [28]:
df2

                   D         B         C         A
2018-02-25 -0.268857 -0.280785  1.255342  0.178941
2018-02-21  0.558963 -0.448283 -0.428961 -0.964640
2018-02-23  1.898996 -0.197857 -0.296553  1.301426
2018-02-24 -0.308144  1.031520  0.737622  0.593048
2018-02-20 -0.253793  1.402828 -0.021302  0.031322
2018-02-22  0.548631 -0.494666  0.448117 -0.338259

In [29]:
df2.sort_index(axis=0)

                   D         B         C         A
2018-02-20 -0.253793  1.402828 -0.021302  0.031322
2018-02-21  0.558963 -0.448283 -0.428961 -0.964640
2018-02-22  0.548631 -0.494666  0.448117 -0.338259
2018-02-23  1.898996 -0.197857 -0.296553  1.301426
2018-02-24 -0.308144  1.031520  0.737622  0.593048
2018-02-25 -0.268857 -0.280785  1.255342  0.178941

In [30]:
df2.sort_index(axis=1)

                   A         B         C         D
2018-02-25  0.178941 -0.280785  1.255342 -0.268857
2018-02-21 -0.964640 -0.448283 -0.428961  0.558963
2018-02-23  1.301426 -0.197857 -0.296553  1.898996
2018-02-24  0.593048  1.031520  0.737622 -0.308144
2018-02-20  0.031322  1.402828 -0.021302 -0.253793
2018-02-22 -0.338259 -0.494666  0.448117  0.548631

In [31]:
df2

                   D         B         C         A
2018-02-25 -0.268857 -0.280785  1.255342  0.178941
2018-02-21  0.558963 -0.448283 -0.428961 -0.964640
2018-02-23  1.898996 -0.197857 -0.296553  1.301426
2018-02-24 -0.308144  1.031520  0.737622  0.593048
2018-02-20 -0.253793  1.402828 -0.021302  0.031322
2018-02-22  0.548631 -0.494666  0.448117 -0.338259

In [32]:
df2.sort_index(axis=0, ascending=False)

                   D         B         C         A
2018-02-25 -0.268857 -0.280785  1.255342  0.178941
2018-02-24 -0.308144  1.031520  0.737622  0.593048
2018-02-23  1.898996 -0.197857 -0.296553  1.301426
2018-02-22  0.548631 -0.494666  0.448117 -0.338259
2018-02-21  0.558963 -0.448283 -0.428961 -0.964640
2018-02-20 -0.253793  1.402828 -0.021302  0.031322

In [33]:
df2.sort_index(axis=1, ascending=False)

                   D         C         B         A
2018-02-25 -0.268857  1.255342 -0.280785  0.178941
2018-02-21  0.558963 -0.428961 -0.448283 -0.964640
2018-02-23  1.898996 -0.296553 -0.197857  1.301426
2018-02-24 -0.308144  0.737622  1.031520  0.593048
2018-02-20 -0.253793 -0.021302  1.402828  0.031322
2018-02-22  0.548631  0.448117 -0.494666 -0.338259

In [34]:
df2

                   D         B         C         A
2018-02-25 -0.268857 -0.280785  1.255342  0.178941
2018-02-21  0.558963 -0.448283 -0.428961 -0.964640
2018-02-23  1.898996 -0.197857 -0.296553  1.301426
2018-02-24 -0.308144  1.031520  0.737622  0.593048
2018-02-20 -0.253793  1.402828 -0.021302  0.031322
2018-02-22  0.548631 -0.494666  0.448117 -0.338259

In [35]:
df2.sort_values(by='D')

                   D         B         C         A
2018-02-24 -0.308144  1.031520  0.737622  0.593048
2018-02-25 -0.268857 -0.280785  1.255342  0.178941
2018-02-20 -0.253793  1.402828 -0.021302  0.031322
2018-02-22  0.548631 -0.494666  0.448117 -0.338259
2018-02-21  0.558963 -0.448283 -0.428961 -0.964640
2018-02-23  1.898996 -0.197857 -0.296553  1.301426

In [36]:
df2.sort_values(by='D', ascending=False)

                   D         B         C         A
2018-02-23  1.898996 -0.197857 -0.296553  1.301426
2018-02-21  0.558963 -0.448283 -0.428961 -0.964640
2018-02-22  0.548631 -0.494666  0.448117 -0.338259
2018-02-20 -0.253793  1.402828 -0.021302  0.031322
2018-02-25 -0.268857 -0.280785  1.255342  0.178941
2018-02-24 -0.308144  1.031520  0.737622  0.593048

In [37]:
df2["E"] = np.random.randint(0, 6, size=6)
df2["F"] = ["first", "second", "first", "third", "first", "second"] 
df2

                   D         B         C         A  E       F
2018-02-25 -0.268857 -0.280785  1.255342  0.178941  3   first
2018-02-21  0.558963 -0.448283 -0.428961 -0.964640  1  second
2018-02-23  1.898996 -0.197857 -0.296553  1.301426  3   first
2018-02-24 -0.308144  1.031520  0.737622  0.593048  4   third
2018-02-20 -0.253793  1.402828 -0.021302  0.031322  2   first
2018-02-22  0.548631 -0.494666  0.448117 -0.338259  3  second

In [38]:
df2.sort_values(by=['E','F'])

                   D         B         C         A  E       F
2018-02-21  0.558963 -0.448283 -0.428961 -0.964640  1  second
2018-02-20 -0.253793  1.402828 -0.021302  0.031322  2   first
2018-02-25 -0.268857 -0.280785  1.255342  0.178941  3   first
2018-02-23  1.898996 -0.197857 -0.296553  1.301426  3   first
2018-02-22  0.548631 -0.494666  0.448117 -0.338259  3  second
2018-02-24 -0.308144  1.031520  0.737622  0.593048  4   third

In [39]:
df2['F'].unique()

array(['first', 'second', 'third'], dtype=object)

In [40]:
df2['F'].value_counts()

F
first     3
second    2
third     1
Name: count, dtype: int64

In [41]:
df3 = pd.DataFrame(np.random.randn(4, 3), columns=["b", "d", "e"],
                   index=["Seoul", "Incheon", "Busan", "Daegu"])  
df3

                b         d         e
Seoul   -0.307744 -1.256248  0.472019
Incheon  0.877185 -0.422856  0.260300
Busan    0.523665  1.190933  1.009931
Daegu    0.254580  0.701506 -0.480946

In [42]:
myFunc = lambda x : x.max() - x.min()

In [43]:
df3.apply(myFunc, axis=0)

b    1.184930
d    2.447181
e    1.490876
dtype: float64

In [45]:
df3.apply(myFunc, axis=1)

Seoul      2.249467
Incheon    1.307894
Busan      3.230163
Daegu      1.215772
dtype: float64

In [47]:
#df3.apply?

- numpy 에서 누적합과 누적곱 구하기

In [48]:
arr = np.array([1,2,3,4,5])

In [49]:
np.cumsum(arr)

array([ 1,  3,  6, 10, 15], dtype=int32)

In [50]:
np.cumprod(arr)

array([  1,   2,   6,  24, 120], dtype=int32)

In [51]:
sr = pd.Series([1,2,3,4,5])

In [52]:
np.cumsum(sr)

0     1
1     3
2     6
3    10
4    15
dtype: int64

In [53]:
np.cumprod(sr)

0      1
1      2
2      6
3     24
4    120
dtype: int64

- pandas 에서 누적합과 누적곱을 구하기

In [54]:
sr.cumsum()

0     1
1     3
2     6
3    10
4    15
dtype: int64

In [55]:
sr.cumprod()

0      1
1      2
2      6
3     24
4    120
dtype: int64