In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.DataFrame(np.random.randn(5,4)) 
df

          0         1         2         3
0 -0.197604 -0.124980  1.218926 -0.295589
1  0.740028 -1.121673 -0.533283 -1.672524
2  0.175790  3.801613  2.086284  0.194440
3  0.168336 -0.332600 -0.075237  1.367948
4  1.803636  0.667766 -1.161403  0.589917

In [3]:
df.columns = ['A','B','C','D']

In [4]:
df

          A         B         C         D
0 -0.197604 -0.124980  1.218926 -0.295589
1  0.740028 -1.121673 -0.533283 -1.672524
2  0.175790  3.801613  2.086284  0.194440
3  0.168336 -0.332600 -0.075237  1.367948
4  1.803636  0.667766 -1.161403  0.589917

In [5]:
df.index = pd.date_range("20200214", periods=5)

In [6]:
df

                   A         B         C         D
2020-02-14 -0.197604 -0.124980  1.218926 -0.295589
2020-02-15  0.740028 -1.121673 -0.533283 -1.672524
2020-02-16  0.175790  3.801613  2.086284  0.194440
2020-02-17  0.168336 -0.332600 -0.075237  1.367948
2020-02-18  1.803636  0.667766 -1.161403  0.589917

In [7]:
type(df.index)

pandas.core.indexes.datetimes.DatetimeIndex

In [8]:
df['E'] = [9.9, np.nan, 10, 9.8, np.nan]

In [9]:
df

                   A         B         C         D     E
2020-02-14 -0.197604 -0.124980  1.218926 -0.295589   9.9
2020-02-15  0.740028 -1.121673 -0.533283 -1.672524   NaN
2020-02-16  0.175790  3.801613  2.086284  0.194440  10.0
2020-02-17  0.168336 -0.332600 -0.075237  1.367948   9.8
2020-02-18  1.803636  0.667766 -1.161403  0.589917   NaN

In [10]:
#df.drop?

In [11]:
#df.dropna?

In [12]:
df.dropna(how='any')

                   A         B         C         D     E
2020-02-14 -0.197604 -0.124980  1.218926 -0.295589   9.9
2020-02-16  0.175790  3.801613  2.086284  0.194440  10.0
2020-02-17  0.168336 -0.332600 -0.075237  1.367948   9.8

In [13]:
df

                   A         B         C         D     E
2020-02-14 -0.197604 -0.124980  1.218926 -0.295589   9.9
2020-02-15  0.740028 -1.121673 -0.533283 -1.672524   NaN
2020-02-16  0.175790  3.801613  2.086284  0.194440  10.0
2020-02-17  0.168336 -0.332600 -0.075237  1.367948   9.8
2020-02-18  1.803636  0.667766 -1.161403  0.589917   NaN

In [14]:
df.dropna(how='all')

                   A         B         C         D     E
2020-02-14 -0.197604 -0.124980  1.218926 -0.295589   9.9
2020-02-15  0.740028 -1.121673 -0.533283 -1.672524   NaN
2020-02-16  0.175790  3.801613  2.086284  0.194440  10.0
2020-02-17  0.168336 -0.332600 -0.075237  1.367948   9.8
2020-02-18  1.803636  0.667766 -1.161403  0.589917   NaN

In [15]:
df.fillna(value=9.7)

                   A         B         C         D     E
2020-02-14 -0.197604 -0.124980  1.218926 -0.295589   9.9
2020-02-15  0.740028 -1.121673 -0.533283 -1.672524   9.7
2020-02-16  0.175790  3.801613  2.086284  0.194440  10.0
2020-02-17  0.168336 -0.332600 -0.075237  1.367948   9.8
2020-02-18  1.803636  0.667766 -1.161403  0.589917   9.7

In [16]:
df

                   A         B         C         D     E
2020-02-14 -0.197604 -0.124980  1.218926 -0.295589   9.9
2020-02-15  0.740028 -1.121673 -0.533283 -1.672524   NaN
2020-02-16  0.175790  3.801613  2.086284  0.194440  10.0
2020-02-17  0.168336 -0.332600 -0.075237  1.367948   9.8
2020-02-18  1.803636  0.667766 -1.161403  0.589917   NaN

In [17]:
df.fillna(value=9.7, inplace=True)

In [18]:
df

                   A         B         C         D     E
2020-02-14 -0.197604 -0.124980  1.218926 -0.295589   9.9
2020-02-15  0.740028 -1.121673 -0.533283 -1.672524   9.7
2020-02-16  0.175790  3.801613  2.086284  0.194440  10.0
2020-02-17  0.168336 -0.332600 -0.075237  1.367948   9.8
2020-02-18  1.803636  0.667766 -1.161403  0.589917   9.7

In [19]:
pd.to_datetime('20200214')

Timestamp('2020-02-14 00:00:00')

In [20]:
df.drop(pd.to_datetime('20200214'))

                   A         B         C         D     E
2020-02-15  0.740028 -1.121673 -0.533283 -1.672524   9.7
2020-02-16  0.175790  3.801613  2.086284  0.194440  10.0
2020-02-17  0.168336 -0.332600 -0.075237  1.367948   9.8
2020-02-18  1.803636  0.667766 -1.161403  0.589917   9.7

In [21]:
df

                   A         B         C         D     E
2020-02-14 -0.197604 -0.124980  1.218926 -0.295589   9.9
2020-02-15  0.740028 -1.121673 -0.533283 -1.672524   9.7
2020-02-16  0.175790  3.801613  2.086284  0.194440  10.0
2020-02-17  0.168336 -0.332600 -0.075237  1.367948   9.8
2020-02-18  1.803636  0.667766 -1.161403  0.589917   9.7

In [22]:
df.drop([pd.to_datetime('20200214') ,pd.to_datetime('20200216')  ])

                   A         B         C         D    E
2020-02-15  0.740028 -1.121673 -0.533283 -1.672524  9.7
2020-02-17  0.168336 -0.332600 -0.075237  1.367948  9.8
2020-02-18  1.803636  0.667766 -1.161403  0.589917  9.7

In [23]:
df

                   A         B         C         D     E
2020-02-14 -0.197604 -0.124980  1.218926 -0.295589   9.9
2020-02-15  0.740028 -1.121673 -0.533283 -1.672524   9.7
2020-02-16  0.175790  3.801613  2.086284  0.194440  10.0
2020-02-17  0.168336 -0.332600 -0.075237  1.367948   9.8
2020-02-18  1.803636  0.667766 -1.161403  0.589917   9.7

In [24]:
df.drop('E', axis=1)

                   A         B         C         D
2020-02-14 -0.197604 -0.124980  1.218926 -0.295589
2020-02-15  0.740028 -1.121673 -0.533283 -1.672524
2020-02-16  0.175790  3.801613  2.086284  0.194440
2020-02-17  0.168336 -0.332600 -0.075237  1.367948
2020-02-18  1.803636  0.667766 -1.161403  0.589917

In [25]:
df

                   A         B         C         D     E
2020-02-14 -0.197604 -0.124980  1.218926 -0.295589   9.9
2020-02-15  0.740028 -1.121673 -0.533283 -1.672524   9.7
2020-02-16  0.175790  3.801613  2.086284  0.194440  10.0
2020-02-17  0.168336 -0.332600 -0.075237  1.367948   9.8
2020-02-18  1.803636  0.667766 -1.161403  0.589917   9.7

In [26]:
df.drop(['B','D'], axis=1)

                   A         C     E
2020-02-14 -0.197604  1.218926   9.9
2020-02-15  0.740028 -0.533283   9.7
2020-02-16  0.175790  2.086284  10.0
2020-02-17  0.168336 -0.075237   9.8
2020-02-18  1.803636 -1.161403   9.7

In [27]:
df.drop(df.index[1])

                   A         B         C         D     E
2020-02-14 -0.197604 -0.124980  1.218926 -0.295589   9.9
2020-02-16  0.175790  3.801613  2.086284  0.194440  10.0
2020-02-17  0.168336 -0.332600 -0.075237  1.367948   9.8
2020-02-18  1.803636  0.667766 -1.161403  0.589917   9.7

In [28]:
df.drop(df.index[[1,3]])

                   A         B         C         D     E
2020-02-14 -0.197604 -0.124980  1.218926 -0.295589   9.9
2020-02-16  0.175790  3.801613  2.086284  0.194440  10.0
2020-02-18  1.803636  0.667766 -1.161403  0.589917   9.7

In [29]:
df.drop(df.index[1:3])

                   A         B         C         D    E
2020-02-14 -0.267886 -0.886824 -0.026843 -2.008512  9.9
2020-02-17 -0.705571  1.410073 -0.611853 -0.038718  9.8
2020-02-18 -2.134847 -0.434059  1.490765  0.588278  9.7

In [30]:
df.drop(df.columns[1:3], axis=1)

                   A         D     E
2020-02-14 -0.267886 -2.008512   9.9
2020-02-15 -0.467916 -0.259222   9.7
2020-02-16  0.235878 -0.077040  10.0
2020-02-17 -0.705571 -0.038718   9.8
2020-02-18 -2.134847  0.588278   9.7

In [31]:
df.drop(df.columns[0], axis=1)

                   B         C         D     E
2020-02-14 -0.886824 -0.026843 -2.008512   9.9
2020-02-15  0.345287  0.288432 -0.259222   9.7
2020-02-16  0.704560  0.774805 -0.077040  10.0
2020-02-17  1.410073 -0.611853 -0.038718   9.8
2020-02-18 -0.434059  1.490765  0.588278   9.7

In [32]:
df

                   A         B         C         D     E
2020-02-14 -0.267886 -0.886824 -0.026843 -2.008512   9.9
2020-02-15 -0.467916  0.345287  0.288432 -0.259222   9.7
2020-02-16  0.235878  0.704560  0.774805 -0.077040  10.0
2020-02-17 -0.705571  1.410073 -0.611853 -0.038718   9.8
2020-02-18 -2.134847 -0.434059  1.490765  0.588278   9.7

In [33]:
df.drop('E', axis=1, inplace=True)
df

                   A         B         C         D
2020-02-14 -0.267886 -0.886824 -0.026843 -2.008512
2020-02-15 -0.467916  0.345287  0.288432 -0.259222
2020-02-16  0.235878  0.704560  0.774805 -0.077040
2020-02-17 -0.705571  1.410073 -0.611853 -0.038718
2020-02-18 -2.134847 -0.434059  1.490765  0.588278