In [1]:
import pandas as pd

In [2]:
data = {"names": ["sunyoung", "sunyoung", "sunyoung", "jungjae", "jungjae"],
           "year": [2024, 2026, 2023, 2025, 2023],
           "points": [2.9, 3.7, 4.6, 5.4, 6.9]}
df = pd.DataFrame(data, columns=["year", "names", "points", "penalty"],
                          index=["one", "two", "three", "four", "five"])

In [3]:
df

       year     names  points penalty
one    2024  sunyoung     2.9     NaN
two    2026  sunyoung     3.7     NaN
three  2023  sunyoung     4.6     NaN
four   2025   jungjae     5.4     NaN
five   2023   jungjae     6.9     NaN

In [4]:
df.names

one      sunyoung
two      sunyoung
three    sunyoung
four      jungjae
five      jungjae
Name: names, dtype: str

In [5]:
df['names']

one      sunyoung
two      sunyoung
three    sunyoung
four      jungjae
five      jungjae
Name: names, dtype: str

In [6]:
df[['names','year']]

          names  year
one    sunyoung  2024
two    sunyoung  2026
three  sunyoung  2023
four    jungjae  2025
five    jungjae  2023

In [7]:
#df[1]
#df['names':'year']

In [8]:
df[1:3] #열번호가 아닌 행번호

       year     names  points penalty
two    2026  sunyoung     3.7     NaN
three  2023  sunyoung     4.6     NaN

In [9]:
df

       year     names  points penalty
one    2024  sunyoung     2.9     NaN
two    2026  sunyoung     3.7     NaN
three  2023  sunyoung     4.6     NaN
four   2025   jungjae     5.4     NaN
five   2023   jungjae     6.9     NaN

In [10]:
df['penalty'] = 0.1

In [11]:
df

       year     names  points  penalty
one    2024  sunyoung     2.9      0.1
two    2026  sunyoung     3.7      0.1
three  2023  sunyoung     4.6      0.1
four   2025   jungjae     5.4      0.1
five   2023   jungjae     6.9      0.1

In [12]:
df['penalty'] = [0.1,0.2,0.3,0.4,0.5]
df

       year     names  points  penalty
one    2024  sunyoung     2.9      0.1
two    2026  sunyoung     3.7      0.2
three  2023  sunyoung     4.6      0.3
four   2025   jungjae     5.4      0.4
five   2023   jungjae     6.9      0.5

In [13]:
import numpy as np

In [14]:
df['rank'] = np.arange(5) 
df

       year     names  points  penalty  rank
one    2024  sunyoung     2.9      0.1     0
two    2026  sunyoung     3.7      0.2     1
three  2023  sunyoung     4.6      0.3     2
four   2025   jungjae     5.4      0.4     3
five   2023   jungjae     6.9      0.5     4

In [ ]:
#del df.rank
#AttributeError: rank

In [15]:
df.rank

<bound method NDFrame.rank of        year     names  points  penalty  rank
one    2024  sunyoung     2.9      0.1     0
two    2026  sunyoung     3.7      0.2     1
three  2023  sunyoung     4.6      0.3     2
four   2025   jungjae     5.4      0.4     3
five   2023   jungjae     6.9      0.5     4>

In [16]:
del df['rank']

In [17]:
df

       year     names  points  penalty
one    2024  sunyoung     2.9      0.1
two    2026  sunyoung     3.7      0.2
three  2023  sunyoung     4.6      0.3
four   2025   jungjae     5.4      0.4
five   2023   jungjae     6.9      0.5

In [18]:
val = pd.Series([-1.2, -1.5, -1.7], index=["two", "four", "five"])

In [19]:
df['debt'] = val

In [20]:
df

       year     names  points  penalty  debt
one    2024  sunyoung     2.9      0.1   NaN
two    2026  sunyoung     3.7      0.2  -1.2
three  2023  sunyoung     4.6      0.3   NaN
four   2025   jungjae     5.4      0.4  -1.5
five   2023   jungjae     6.9      0.5  -1.7

In [21]:
df['net_points'] = df['points'] - df['penalty']

In [22]:
df

       year     names  points  penalty  debt  net_points
one    2024  sunyoung     2.9      0.1   NaN         2.8
two    2026  sunyoung     3.7      0.2  -1.2         3.5
three  2023  sunyoung     4.6      0.3   NaN         4.3
four   2025   jungjae     5.4      0.4  -1.5         5.0
five   2023   jungjae     6.9      0.5  -1.7         6.4

In [23]:
df['high_points'] = df['net_points'] > 4.0

In [24]:
df

       year     names  points  penalty  debt  net_points  high_points
one    2024  sunyoung     2.9      0.1   NaN         2.8        False
two    2026  sunyoung     3.7      0.2  -1.2         3.5        False
three  2023  sunyoung     4.6      0.3   NaN         4.3         True
four   2025   jungjae     5.4      0.4  -1.5         5.0         True
five   2023   jungjae     6.9      0.5  -1.7         6.4         True

In [25]:
del df['net_points']

In [26]:
del df["high_points"]

In [27]:
df.columns

Index(['year', 'names', 'points', 'penalty', 'debt'], dtype='str')

In [28]:
df

       year     names  points  penalty  debt
one    2024  sunyoung     2.9      0.1   NaN
two    2026  sunyoung     3.7      0.2  -1.2
three  2023  sunyoung     4.6      0.3   NaN
four   2025   jungjae     5.4      0.4  -1.5
five   2023   jungjae     6.9      0.5  -1.7

In [30]:
df.index.name = "Order"

In [31]:
df.columns.name="Info"

In [32]:
df

Info   year     names  points  penalty  debt
Order
one    2024  sunyoung     2.9      0.1   NaN
two    2026  sunyoung     3.7      0.2  -1.2
three  2023  sunyoung     4.6      0.3   NaN
four   2025   jungjae     5.4      0.4  -1.5
five   2023   jungjae     6.9      0.5  -1.7

In [33]:
df[0:3]

Info   year     names  points  penalty  debt
Order
one    2024  sunyoung     2.9      0.1   NaN
two    2026  sunyoung     3.7      0.2  -1.2
three  2023  sunyoung     4.6      0.3   NaN

In [34]:
df["two":"four"]

Info   year     names  points  penalty  debt
Order
two    2026  sunyoung     3.7      0.2  -1.2
three  2023  sunyoung     4.6      0.3   NaN
four   2025   jungjae     5.4      0.4  -1.5

In [35]:
#df[["two","four"]] 
#df["two"]
#df[1]

In [36]:
df.loc["two"]

Info
year           2026
names      sunyoung
points          3.7
penalty         0.2
debt           -1.2
Name: two, dtype: object

In [37]:
df.loc["two", : ]

Info
year           2026
names      sunyoung
points          3.7
penalty         0.2
debt           -1.2
Name: two, dtype: object

In [38]:
df.loc[["two","four"], :]

Info   year     names  points  penalty  debt
Order
two    2026  sunyoung     3.7      0.2  -1.2
four   2025   jungjae     5.4      0.4  -1.5

In [39]:
df.loc[ "two", "year":"points"]

Info
year          2026
names     sunyoung
points         3.7
Name: two, dtype: object

In [40]:
df.loc[:, "year"]

Order
one      2024
two      2026
three    2023
four     2025
five     2023
Name: year, dtype: int64

In [41]:
df.loc[ 'two':'four',"year" :"points"]

Info   year     names  points
Order
two    2026  sunyoung     3.7
three  2023  sunyoung     4.6
four   2025   jungjae     5.4

In [42]:
df

Info   year     names  points  penalty  debt
Order
one    2024  sunyoung     2.9      0.1   NaN
two    2026  sunyoung     3.7      0.2  -1.2
three  2023  sunyoung     4.6      0.3   NaN
four   2025   jungjae     5.4      0.4  -1.5
five   2023   jungjae     6.9      0.5  -1.7

In [43]:
df.loc["six" , : ] = [2020, "pyosunyoung", 9.9, 0.1, np.nan]

In [44]:
df

Info     year        names  points  penalty  debt
Order
one    2024.0     sunyoung     2.9      0.1   NaN
two    2026.0     sunyoung     3.7      0.2  -1.2
three  2023.0     sunyoung     4.6      0.3   NaN
four   2025.0      jungjae     5.4      0.4  -1.5
five   2023.0      jungjae     6.9      0.5  -1.7
six    2020.0  pyosunyoung     9.9      0.1   NaN

In [45]:
df['year'] = df['year'].astype('int32')

In [46]:
df

Info   year        names  points  penalty  debt
Order
one    2024     sunyoung     2.9      0.1   NaN
two    2026     sunyoung     3.7      0.2  -1.2
three  2023     sunyoung     4.6      0.3   NaN
four   2025      jungjae     5.4      0.4  -1.5
five   2023      jungjae     6.9      0.5  -1.7
six    2020  pyosunyoung     9.9      0.1   NaN

In [47]:
df.iloc[1, 0:2]

Info
year         2026
names    sunyoung
Name: two, dtype: object

In [48]:
df.iloc[1,2]

np.float64(3.7)

In [49]:
df.iloc[3]

Info
year          2025
names      jungjae
points         5.4
penalty        0.4
debt          -1.5
Name: four, dtype: object

In [50]:
df.iloc[ 3:5, 0:2]

Info   year    names
Order
four   2025  jungjae
five   2023  jungjae

In [51]:
df.iloc[ [0,1,3],[1,3]]

Info      names  penalty
Order
one    sunyoung      0.1
two    sunyoung      0.2
four    jungjae      0.4

In [52]:
df.iloc[ : , 1:4]

Info         names  points  penalty
Order
one       sunyoung     2.9      0.1
two       sunyoung     3.7      0.2
three     sunyoung     4.6      0.3
four       jungjae     5.4      0.4
five       jungjae     6.9      0.5
six    pyosunyoung     9.9      0.1

In [53]:
df

Info   year        names  points  penalty  debt
Order
one    2024     sunyoung     2.9      0.1   NaN
two    2026     sunyoung     3.7      0.2  -1.2
three  2023     sunyoung     4.6      0.3   NaN
four   2025      jungjae     5.4      0.4  -1.5
five   2023      jungjae     6.9      0.5  -1.7
six    2020  pyosunyoung     9.9      0.1   NaN

In [54]:
df['year'] > 2017

Order
one      True
two      True
three    True
four     True
five     True
six      True
Name: year, dtype: bool

In [55]:
df.loc[df['year']>2017 , : ]

Info   year        names  points  penalty  debt
Order
one    2024     sunyoung     2.9      0.1   NaN
two    2026     sunyoung     3.7      0.2  -1.2
three  2023     sunyoung     4.6      0.3   NaN
four   2025      jungjae     5.4      0.4  -1.5
five   2023      jungjae     6.9      0.5  -1.7
six    2020  pyosunyoung     9.9      0.1   NaN

In [56]:
df.loc[df['year']>2017 , ['names','points']]

Info         names  points
Order
one       sunyoung     2.9
two       sunyoung     3.7
three     sunyoung     4.6
four       jungjae     5.4
five       jungjae     6.9
six    pyosunyoung     9.9

In [57]:
df

Info   year        names  points  penalty  debt
Order
one    2024     sunyoung     2.9      0.1   NaN
two    2026     sunyoung     3.7      0.2  -1.2
three  2023     sunyoung     4.6      0.3   NaN
four   2025      jungjae     5.4      0.4  -1.5
five   2023      jungjae     6.9      0.5  -1.7
six    2020  pyosunyoung     9.9      0.1   NaN

In [58]:
df.loc[ df['names']=='sunyoung', ['names','year'] ]

Info      names  year
Order
one    sunyoung  2024
two    sunyoung  2026
three  sunyoung  2023

In [59]:
df.loc[ (df['points'] > 3) & (df['points'] < 9), :  ]

Info   year     names  points  penalty  debt
Order
two    2026  sunyoung     3.7      0.2  -1.2
three  2023  sunyoung     4.6      0.3   NaN
four   2025   jungjae     5.4      0.4  -1.5
five   2023   jungjae     6.9      0.5  -1.7

In [60]:
df

Info   year        names  points  penalty  debt
Order
one    2024     sunyoung     2.9      0.1   NaN
two    2026     sunyoung     3.7      0.2  -1.2
three  2023     sunyoung     4.6      0.3   NaN
four   2025      jungjae     5.4      0.4  -1.5
five   2023      jungjae     6.9      0.5  -1.7
six    2020  pyosunyoung     9.9      0.1   NaN

In [61]:
df.loc[ df['points'] > 6 , 'penalty'] = 0

In [62]:
df

Info   year        names  points  penalty  debt
Order
one    2024     sunyoung     2.9      0.1   NaN
two    2026     sunyoung     3.7      0.2  -1.2
three  2023     sunyoung     4.6      0.3   NaN
four   2025      jungjae     5.4      0.4  -1.5
five   2023      jungjae     6.9      0.0  -1.7
six    2020  pyosunyoung     9.9      0.0   NaN