In [ ]:
import numpy as np
import pandas as pd

In [ ]:
data = [[9.9, 8.8], [np.nan, 6.6],[7.7, np.nan],  [0.99, 9.8]]
df = pd.DataFrame(data, columns=["first", "second"], index=["a", "b", "c", "d"])

In [4]:
df

   first  second
a   9.90     8.8
b    NaN     6.6
c   7.70     NaN
d   0.99     9.8

In [5]:
df.sum(axis=0)

first     18.59
second    25.20
dtype: float64

In [ ]:
#df.sum?

In [6]:
df.sum(axis=0, skipna=False)

first    NaN
second   NaN
dtype: float64

In [7]:
df.sum(axis=1)

a    18.70
b     6.60
c     7.70
d    10.79
dtype: float64

In [ ]:
df.sum(axis=1, skipna=False)

In [8]:
df

   first  second
a   9.90     8.8
b    NaN     6.6
c   7.70     NaN
d   0.99     9.8

In [9]:
df.describe()

          first    second
count  3.000000  3.000000
mean   6.196667  8.400000
std    4.641340  1.637071
min    0.990000  6.600000
25%    4.345000  7.700000
50%    7.700000  8.800000
75%    8.800000  9.300000
max    9.900000  9.800000

In [10]:
df

   first  second
a   9.90     8.8
b    NaN     6.6
c   7.70     NaN
d   0.99     9.8

In [11]:
df['first'].sum()

np.float64(18.59)

In [12]:
df.loc['a'].sum()

np.float64(18.700000000000003)

In [13]:
df.mean(axis=1)

a    9.350
b    6.600
c    7.700
d    5.395
dtype: float64

In [14]:
df

   first  second
a   9.90     8.8
b    NaN     6.6
c   7.70     NaN
d   0.99     9.8

In [15]:
first_mean = df.mean(axis=0)['first']

In [16]:
second_min = df.min(axis=0)['second']

In [17]:
df['first'] = df['first'].fillna(value=first_mean)

In [18]:
df['second'] = df['second'].fillna(value=second_min)

In [19]:
df

      first  second
a  9.900000     8.8
b  6.196667     6.6
c  7.700000     6.6
d  0.990000     9.8

In [20]:
df2 = pd.DataFrame(np.random.randn(6, 4),
                   columns=["A", "B", "C", "D"],
                   index=pd.date_range("20180220", periods=6)) 
df2

                   A         B         C         D
2018-02-20 -0.848446  1.145264 -0.410180 -0.151619
2018-02-21  0.531579  1.592101  0.399200 -1.708121
2018-02-22 -0.416324 -0.324618  1.343178  1.386580
2018-02-23  0.163500  1.055669  0.281616 -1.740054
2018-02-24  1.152486  0.160500 -0.034107  0.289515
2018-02-25 -0.457925 -1.759746 -0.914058 -0.440576

In [21]:
df2['A'].corr(df2['B'])

np.float64(0.248559897225291)

In [ ]:
df2['A'].corr(df2['C'])

In [ ]:
df2['A'].corr(df2['D'])

In [23]:
df2.corr() # 상관계수

          A         B         C         D
A  1.000000  0.248560  0.144557 -0.237346
B  0.248560  1.000000  0.299142 -0.488150
C  0.144557  0.299142  1.000000  0.303461
D -0.237346 -0.488150  0.303461  1.000000

In [24]:
df2.cov() # 공분산

          A         B         C         D
A  0.547563  0.226857  0.082495 -0.211302
B  0.226857  1.521280  0.284549 -0.724374
C  0.082495  0.284549  0.594772  0.281568
D -0.211302 -0.724374  0.281568  1.447470

In [25]:
dates = df2.index
# permutation 은 치환
random_dates = np.random.permutation(dates)
# 무작위로 섞어봄. index 순서와 컬럼의 순서가 불규칙하게 변함
df2 = df2.reindex(index=random_dates, columns=["D", "B", "C", "A"])

In [26]:
df2

                   D         B         C         A
2018-02-24  0.289515  0.160500 -0.034107  1.152486
2018-02-23 -1.740054  1.055669  0.281616  0.163500
2018-02-25 -0.440576 -1.759746 -0.914058 -0.457925
2018-02-22  1.386580 -0.324618  1.343178 -0.416324
2018-02-20 -0.151619  1.145264 -0.410180 -0.848446
2018-02-21 -1.708121  1.592101  0.399200  0.531579

In [27]:
df2.sort_index(axis=0)

                   D         B         C         A
2018-02-20 -0.151619  1.145264 -0.410180 -0.848446
2018-02-21 -1.708121  1.592101  0.399200  0.531579
2018-02-22  1.386580 -0.324618  1.343178 -0.416324
2018-02-23 -1.740054  1.055669  0.281616  0.163500
2018-02-24  0.289515  0.160500 -0.034107  1.152486
2018-02-25 -0.440576 -1.759746 -0.914058 -0.457925

In [28]:
df2.sort_index(axis=1)

                   A         B         C         D
2018-02-24  1.152486  0.160500 -0.034107  0.289515
2018-02-23  0.163500  1.055669  0.281616 -1.740054
2018-02-25 -0.457925 -1.759746 -0.914058 -0.440576
2018-02-22 -0.416324 -0.324618  1.343178  1.386580
2018-02-20 -0.848446  1.145264 -0.410180 -0.151619
2018-02-21  0.531579  1.592101  0.399200 -1.708121

In [29]:
df2

                   D         B         C         A
2018-02-24  0.289515  0.160500 -0.034107  1.152486
2018-02-23 -1.740054  1.055669  0.281616  0.163500
2018-02-25 -0.440576 -1.759746 -0.914058 -0.457925
2018-02-22  1.386580 -0.324618  1.343178 -0.416324
2018-02-20 -0.151619  1.145264 -0.410180 -0.848446
2018-02-21 -1.708121  1.592101  0.399200  0.531579

In [30]:
df2.sort_index(axis=0, ascending=False)

                   D         B         C         A
2018-02-25 -0.440576 -1.759746 -0.914058 -0.457925
2018-02-24  0.289515  0.160500 -0.034107  1.152486
2018-02-23 -1.740054  1.055669  0.281616  0.163500
2018-02-22  1.386580 -0.324618  1.343178 -0.416324
2018-02-21 -1.708121  1.592101  0.399200  0.531579
2018-02-20 -0.151619  1.145264 -0.410180 -0.848446

In [31]:
df2.sort_index(axis=1, ascending=False)

                   D         C         B         A
2018-02-24  0.289515 -0.034107  0.160500  1.152486
2018-02-23 -1.740054  0.281616  1.055669  0.163500
2018-02-25 -0.440576 -0.914058 -1.759746 -0.457925
2018-02-22  1.386580  1.343178 -0.324618 -0.416324
2018-02-20 -0.151619 -0.410180  1.145264 -0.848446
2018-02-21 -1.708121  0.399200  1.592101  0.531579

In [32]:
df2

                   D         B         C         A
2018-02-24  0.289515  0.160500 -0.034107  1.152486
2018-02-23 -1.740054  1.055669  0.281616  0.163500
2018-02-25 -0.440576 -1.759746 -0.914058 -0.457925
2018-02-22  1.386580 -0.324618  1.343178 -0.416324
2018-02-20 -0.151619  1.145264 -0.410180 -0.848446
2018-02-21 -1.708121  1.592101  0.399200  0.531579

In [33]:
df2.sort_values(by='D')

                   D         B         C         A
2018-02-23 -1.740054  1.055669  0.281616  0.163500
2018-02-21 -1.708121  1.592101  0.399200  0.531579
2018-02-25 -0.440576 -1.759746 -0.914058 -0.457925
2018-02-20 -0.151619  1.145264 -0.410180 -0.848446
2018-02-24  0.289515  0.160500 -0.034107  1.152486
2018-02-22  1.386580 -0.324618  1.343178 -0.416324

In [34]:
df2.sort_values(by='D', ascending=False)

                   D         B         C         A
2018-02-22  1.386580 -0.324618  1.343178 -0.416324
2018-02-24  0.289515  0.160500 -0.034107  1.152486
2018-02-20 -0.151619  1.145264 -0.410180 -0.848446
2018-02-25 -0.440576 -1.759746 -0.914058 -0.457925
2018-02-21 -1.708121  1.592101  0.399200  0.531579
2018-02-23 -1.740054  1.055669  0.281616  0.163500

In [35]:
df2["E"] = np.random.randint(0, 6, size=6)
df2["F"] = ["first", "second", "first", "third", "first", "second"] 
df2

                   D         B         C         A  E       F
2018-02-24  0.289515  0.160500 -0.034107  1.152486  5   first
2018-02-23 -1.740054  1.055669  0.281616  0.163500  1  second
2018-02-25 -0.440576 -1.759746 -0.914058 -0.457925  5   first
2018-02-22  1.386580 -0.324618  1.343178 -0.416324  0   third
2018-02-20 -0.151619  1.145264 -0.410180 -0.848446  2   first
2018-02-21 -1.708121  1.592101  0.399200  0.531579  2  second

In [36]:
df2.sort_values(by=['E','F'])

                   D         B         C         A  E       F
2018-02-22  1.386580 -0.324618  1.343178 -0.416324  0   third
2018-02-23 -1.740054  1.055669  0.281616  0.163500  1  second
2018-02-20 -0.151619  1.145264 -0.410180 -0.848446  2   first
2018-02-21 -1.708121  1.592101  0.399200  0.531579  2  second
2018-02-24  0.289515  0.160500 -0.034107  1.152486  5   first
2018-02-25 -0.440576 -1.759746 -0.914058 -0.457925  5   first

In [37]:
df2['F'].unique()

<StringArray>
['first', 'second', 'third']
Length: 3, dtype: str

In [38]:
df2['F'].value_counts()

F
first     3
second    2
third     1
Name: count, dtype: int64

In [39]:
df3 = pd.DataFrame(np.random.randn(4, 3), columns=["b", "d", "e"],
                   index=["Seoul", "Incheon", "Busan", "Daegu"])  
df3

                b         d         e
Seoul   -0.602166  1.727312 -2.290284
Incheon  0.258564  2.091607  0.971964
Busan   -0.126076  1.108870  1.365845
Daegu   -1.293407  1.242010 -1.230851

In [40]:
myFunc = lambda x : x.max() - x.min()

In [41]:
df3.apply(myFunc, axis=0)

b    1.551971
d    0.982737
e    3.656129
dtype: float64

In [42]:
df3.apply(myFunc, axis=1)

Seoul      4.017596
Incheon    1.833043
Busan      1.491921
Daegu      2.535416
dtype: float64

In [ ]:
#df3.apply?

- numpy 에서 누적합과 누적곱 구하기

In [43]:
arr = np.array([1,2,3,4,5])

In [44]:
np.cumsum(arr)

array([ 1,  3,  6, 10, 15])

In [45]:
np.cumprod(arr)

array([  1,   2,   6,  24, 120])

In [46]:
sr = pd.Series([1,2,3,4,5])

In [47]:
np.cumsum(sr)

0     1
1     3
2     6
3    10
4    15
dtype: int64

In [48]:
np.cumprod(sr)

0      1
1      2
2      6
3     24
4    120
dtype: int64

- pandas 에서 누적합과 누적곱을 구하기

In [49]:
sr.cumsum()

0     1
1     3
2     6
3    10
4    15
dtype: int64

In [50]:
sr.cumprod()

0      1
1      2
2      6
3     24
4    120
dtype: int64