In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.DataFrame({'key1' : ['a', 'a', 'b', 'b', 'a'],
                   'key2' : ['one', 'two', 'one', 'two', 'one'],
                   'data1': np.random.randn(5),
                   'data2': np.random.randn(5)})
df

  key1 key2     data1     data2
0    a  one  0.006006  0.789828
1    a  two  0.789336 -0.114988
2    b  one  0.919368 -1.951511
3    b  two -0.155408  0.957220
4    a  one  0.384740 -0.513812

In [3]:
grouped = df['data1'].groupby(df['key1'])

In [4]:
grouped

In [5]:
grouped.mean()

key1
a    0.393361
b    0.381980
Name: data1, dtype: float64

In [6]:
#df.groupby?

In [7]:
df

  key1 key2     data1     data2
0    a  one  0.006006  0.789828
1    a  two  0.789336 -0.114988
2    b  one  0.919368 -1.951511
3    b  two -0.155408  0.957220
4    a  one  0.384740 -0.513812

In [8]:
means = df['data1'].groupby([df['key1'], df['key2']]).mean()
means

key1  key2
a     one     0.195373
      two     0.789336
b     one     0.919368
      two    -0.155408
Name: data1, dtype: float64

In [9]:
means.unstack()

key2       one       two
key1
a     0.195373  0.789336
b     0.919368 -0.155408

In [10]:
df

  key1 key2     data1     data2
0    a  one  0.006006  0.789828
1    a  two  0.789336 -0.114988
2    b  one  0.919368 -1.951511
3    b  two -0.155408  0.957220
4    a  one  0.384740 -0.513812

In [11]:
df.groupby('key1').mean(numeric_only=True)

         data1     data2
key1
a     0.393361  0.053676
b     0.381980 -0.497145

In [12]:
df['data1'].groupby(df['key1']).mean()

key1
a    0.393361
b    0.381980
Name: data1, dtype: float64

In [13]:
#df['data1'].groupby('key1').mean() #에러

In [14]:
df.groupby(['key1','key2']).count()

           data1  data2
key1 key2
a    one       2      2
     two       1      1
b    one       1      1
     two       1      1

In [15]:
for name, group in df.groupby('key1'):
    print(name)
    print(group)

a
  key1 key2     data1     data2
0    a  one  0.006006  0.789828
1    a  two  0.789336 -0.114988
4    a  one  0.384740 -0.513812
b
  key1 key2     data1     data2
2    b  one  0.919368 -1.951511
3    b  two -0.155408  0.957220

In [16]:
print(df.groupby('key1'))

<pandas.core.groupby.generic.DataFrameGroupBy object at 0x000001CFB6CC88A0>

In [17]:
df2 = pd.DataFrame(np.random.randn(5, 5), 
                   columns=['a', 'b', 'c', 'd', 'e'],
                   index=['Joe', 'Steve', 'Wes', 'Jim', 'Travis'])

In [18]:
df2

               a         b         c         d         e
Joe     2.023494  0.418874 -0.610463 -1.294151  1.503301
Steve   0.515533  0.522106 -0.270366  0.062524  0.164427
Wes    -0.812176 -0.242873  0.420459 -0.011638 -0.371151
Jim    -0.593553 -2.149519  0.037531 -0.935524 -0.498248
Travis  0.216822  0.013568 -0.203431  2.564431  1.060501

In [19]:
map_dict = {'a':'red', 'b':'blue', 'c':'red', 'd':'blue', 'e':'red', 'f':'gold'}

In [20]:
df2.groupby(map_dict, axis=1).sum()

C:\Users\yhkim\AppData\Local\Temp\ipykernel_59084\1465586691.py:1: FutureWarning: DataFrame.groupby with axis=1 is deprecated. Do `frame.T.groupby(...)` without axis instead.
  df2.groupby(map_dict, axis=1).sum()

            blue       red
Joe    -0.875277  2.916333
Steve   0.584630  0.409593
Wes    -0.254512 -0.762867
Jim    -3.085044 -1.054271
Travis  2.577999  1.073891

In [21]:
grouped

In [22]:
grouped.describe()

,count,mean,std,min,25%,50%,75%,max
key1,,,,,,,,
a,3.0,0.393361,0.391736,0.006006,0.195373,0.38474,0.587038,0.789336
b,2.0,0.381980,0.759981,-0.155408,0.113286,0.38198,0.650674,0.919368