In [1]:
import pandas as pd

In [2]:
sr1 = pd.Series([10, -1, 9, 7, -8])

In [3]:
#pd.Series?

In [4]:
sr1

0    10
1    -1
2     9
3     7
4    -8
dtype: int64

In [5]:
type(sr1)

pandas.core.series.Series

In [6]:
sr1.index

RangeIndex(start=0, stop=5, step=1)

In [7]:
sr1.values

array([10, -1,  9,  7, -8])

In [8]:
sr1.dtype

dtype('int64')

In [9]:
sr2 = pd.Series([10, -1, 9, 7, -8], index=['a','b','c','d','e'])
sr2

a    10
b    -1
c     9
d     7
e    -8
dtype: int64

In [10]:
sd = {'sunyoung':999999, 'kildong':100000, 'jungsun' : 9990000, 'jungjae':888999}

In [11]:
type(sd)

dict

In [12]:
sr3 = pd.Series(sd)

In [13]:
sr3

sunyoung     999999
kildong      100000
jungsun     9990000
jungjae      888999
dtype: int64

In [14]:
data = { 'names' : ['sunyoung', 'sunyoung', 'sunyoung', 'jungjae','jungjae'] ,
       'year' : [2016, 2017, 2018, 2019, 2016],
       'points' : [1.5, 1.7, 3.6, 2.4, 5.7]}

In [15]:
df = pd.DataFrame(data)
df

      names  year  points
0  sunyoung  2016     1.5
1  sunyoung  2017     1.7
2  sunyoung  2018     3.6
3   jungjae  2019     2.4
4   jungjae  2016     5.7

In [16]:
df.index

RangeIndex(start=0, stop=5, step=1)

In [17]:
df.columns

Index(['names', 'year', 'points'], dtype='object')

In [18]:
df.values

array([['sunyoung', 2016, 1.5],
       ['sunyoung', 2017, 1.7],
       ['sunyoung', 2018, 3.6],
       ['jungjae', 2019, 2.4],
       ['jungjae', 2016, 5.7]], dtype=object)

In [19]:
df

      names  year  points
0  sunyoung  2016     1.5
1  sunyoung  2017     1.7
2  sunyoung  2018     3.6
3   jungjae  2019     2.4
4   jungjae  2016     5.7

In [20]:
df2 = pd.DataFrame(data, columns=['year', 'names', 'points', 'penalty'],
                  index=['one','two','three','four','five'])
df2

       year     names  points penalty
one    2016  sunyoung     1.5     NaN
two    2017  sunyoung     1.7     NaN
three  2018  sunyoung     3.6     NaN
four   2019   jungjae     2.4     NaN
five   2016   jungjae     5.7     NaN